### PR TITLE
#160233942 Add feature to update food order status

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Updates a food order matching the provided orderID

#### Description of Task to be completed?

* Creates and tests an RESTful API endpoint
`PUT /api/v1/orders/<orderID>`

#### How the app should be tested
* Set Install, setup and configure the development enviroment.
1. Install [python3](https://www.python.org/download/releases/3.6.4/)
2. [Pipenv & Virtual Environments](http://docs.python-guide.org/en/latest/dev/virtualenvs/)
3. On a  terminal (Linux), Install and set up git `sudo apt install git` 

4.  Clone the repository `git clone https://github.com/artorious/speedy_chakula_app.git`

5. Run `cd speedy_chakula_app/`

6. Run `git checkout ft-update-food-order-160233942`

7. In a virutal environment, run `pipenv shell` to install requirements

8. Test the code `coverage run -m pytest -v app/tests/test* ; coverage report app/tests/test_*  app/*.py `

9. run `FLASK_APP=run.py ; flask run`

10. Test endpoint on  [Postman](https://www.getpostman.com/collections/dbfd44a4306fe46d66a4) 

#### Any background context you want to provide?
API endpoint  uses data structures  to store data in memory 

#### What are the relevant pivotal tracker stories?
[Failing unit Tests](https://www.pivotaltracker.com/story/show/160233942)
[Passing unit Tests](https://www.pivotaltracker.com/story/show/160234323)

#### Screenshots 
screenshot from 2018-09-07 11-27-49
screenshot from 2018-09-07 11-37-09
screenshot from 2018-09-07 11-37-35
screenshot from 2018-09-07 11-37-44
screenshot from 2018-09-07 11-38-21
screenshot from 2018-09-07 11-38-37
screenshot from 2018-09-07 11-38-47
screenshot from 2018-09-07 11-39-09

### CODE REVIEW

**Comment by jeffnyalik** [comment]
Nice one, just noted are you using unittest for the application.

**Comment by Kalela** [comment]
I think you can put the Pipfile.lock in your .gitignore. What do you think?

**Comment by artorious** [comment]
> I think you can put the Pipfile.lock in your .gitignore. What do you think?

Hi, I've been thinking on that myself. Following the discussion on the same issue in  https://github.com/pypa/pipenv/issues/598 it seems that tracking the pipfile is recomended. Pls Advise....

**Comment by Kalela** [comment]
I think it's fine having it there. We can always remove it later on if it causes any trouble.

**Comment by Kalela** [comment]
LGTM. I'm merging this now.

**Pull request merged**
