### PR TITLE
#160231913 Fetch all orders 

### PR DESCRIPTION
**Pull request by artorious**
#### What does this PR do?

* Fetches all available food orders

#### Description of Task to be completed?

* Creates and tests an RESTful API endpoint
`GET /api/v1/orders`

#### How the app should be tested
* Set Install, setup and configure the development enviroment.
1. Install [python3](https://www.python.org/download/releases/3.6.4/)
2. [Pipenv & Virtual Environments](http://docs.python-guide.org/en/latest/dev/virtualenvs/)
3. On a  terminal (Linux), Install and set up git `sudo apt install git` 

4.  Clone the repository `git clone https://github.com/artorious/speedy_chakula_app.git`

5. Run `cd speedy_chakula_app/`

6. Run `git checkout ft-fetch-all-orders-160231913`

7. In a virutal environment, run `pipenv shell` to install requirements

8. Test the code `coverage run -m pytest -v app/tests/test* ; coverage report app/tests/test_*  app/*.py `

9. run `FLASK_APP=run.py ; flask run`

10. Test endpoint on  [Postman](https://www.getpostman.com/collections/dbfd44a4306fe46d66a4) or on terminal, run `curl  --include http://127.0.0.1:5000/api/v1/orders`. 

#### Any background context you want to provide?
API endpoint  uses data structures  to store data in memory 

#### What are the relevant pivotal tracker stories?
[Failing unit Tests](https://www.pivotaltracker.com/story/show/160231913)
[Passing unit Tests](https://www.pivotaltracker.com/story/show/160232168)

#### Screenshots 

screenshot from 2018-09-04 19-17-44

screenshot from 2018-09-05 11-22-51

### CODE REVIEW

**Comment by CkCreative** [comment]
Good work @artorious

**Comment by PromasterGuru** [comment]
Awesome

**Comment by calebrotich** [comment]
Nice

**Comment by ogol254** [comment]
I can see you are testing even the tests themselves

**Comment by Kalela** [comment]
LGTM

**Pull request merged**
